apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egai-pvc
  annotations:
    helm.sh/resource-policy: {{ .Values.global.pvc_policy }} #keep  to Prevent Helm from deleting PVC on uninstall
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.pvc.size }}
